apiVersion: v1
kind: Service
metadata:
  name: zookeeper-server
  labels:
    app.kubernetes.io/name: zookeeper
    app.kubernetes.io/part-of: nifi
spec:
  ports:
  - port: 2888
    name: server
  - port: 3888
    name: leader-election
  clusterIP: None
  selector:
    app.kubernetes.io/name: zookeeper
