apiVersion: v1
kind: Service
metadata:
  name: zookeeper-client
  labels:
    app.kubernetes.io/name: zookeeper
    app.kubernetes.io/part-of: nifi
spec:
  ports:
  - port: 2181
    name: client
  selector:
    app.kubernetes.io/name: zookeeper