---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: nifi
  labels:
    app.kubernetes.io/name: nifi
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nifi
  minReplicas: 2
  maxReplicas: 8
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 300
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 90
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 90
