apiVersion: v1
kind: ConfigMap
metadata:
  name: nifi-cm
data:
  NIFI_JVM_HEAP_INIT: "512m"
  NIFI_JVM_HEAP_MAX: "2g"

  NIFI_WEB_HTTPS_PORT: "8443"
  NIFI_WEB_PROXY_HOST: "nifi:8443"

  NIFI_SENSITIVE_PROPS_KEY: "th1s1s3up34e5r37"

  NIFI_CLUSTER_IS_NODE: "true"
  NIFI_CLUSTER_NODE_PROTOCOL_PORT: "11443"
  NIFI_CLUSTER_NODE_PROTOCOL_MAX_THREADS: "50"
  NIFI_CLUSTER_LEADER_ELECTION_IMPLEMENTATION: "KubernetesLeaderElectionManager"
  NIFI_STATE_MANAGEMENT_PROVIDER_CLUSTER: "kubernetes-provider"
  NIFI_ELECTION_MAX_WAIT: "5 mins"
  NIFI_ELECTION_MAX_CANDIDATES: "2"

  SINGLE_USER_CREDENTIALS_USERNAME: "admin"
  SINGLE_USER_CREDENTIALS_PASSWORD: "Password123456"
