---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nifi
  labels:
    name: nifi
    app: nifi
  annotations:
    app.kubernetes.io/name: nifi
    app.kubernetes.io/part-of: nifi
spec:
  revisionHistoryLimit: 1
  serviceName: nifi
  podManagementPolicy: OrderedReady
  selector:
    matchLabels:
      app: nifi
  template:
    metadata:
      labels:
        app: nifi
    spec:
      serviceAccountName: nifi
      automountServiceAccountToken: true
      enableServiceLinks: false
      setHostnameAsFQDN: true
      dnsPolicy: ClusterFirstWithHostNet
      restartPolicy: Always
      securityContext:
        runAsGroup: 1000
        runAsUser: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      initContainers:
        - name: fix-permissions
          image: docker.io/busybox:1.37
          command:
          - sh
          - -c
          - |
            chmod -R 777 /certs
            chown -R 1000:1000 /certs
          volumeMounts:
          - name: certs
            mountPath: /certs
          securityContext:
            runAsUser: 0
            runAsNonRoot: false
            allowPrivilegeEscalation: false
            privileged: false
            capabilities:
              drop:
                - ALL
              add:
                - CHOWN
                - FOWNER
        - name: wait-for-zookeeper
          image: docker.io/busybox:1.37
          command:
          - sh
          - -c
          - |
            echo "Connecting to Zookeeper ${NIFI_ZK_CONNECT_STRING}"
            until nc -vzw 1 zookeeper 2181 ; do
              echo "Waiting for zookeeper to start"
              sleep 3
            done
          envFrom:
          - configMapRef:
              name: nifi-cm
              optional: false
          resources:
            requests:
              cpu: 20m
              memory: 10Mi
            limits:
              cpu: 20m
              memory: 10Mi
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
        - name: security-setup
          image: docker.io/apache/nifi:2.7.2
          command:
          - /bin/bash
          - /scripts/security.sh
          env:
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          envFrom:
          - configMapRef:
              name: nifi-cm
              optional: false
          volumeMounts:
          - name: certs
            mountPath: /certs
          - name: scripts
            mountPath: /scripts/security.sh
            subPath: security.sh
      containers:
      - name: nifi
        image: docker.io/apache/nifi:2.7.2
        imagePullPolicy: IfNotPresent
        command:
          - /bin/bash
          - -c
          - |
            echo "Applying custom configuration..."
            # Ensure paths and passwords are set correctly in nifi.properties
            sed -i 's|nifi.security.keystore=.*|nifi.security.keystore=./conf/keystore.p12|' /opt/nifi/nifi-current/conf/nifi.properties
            sed -i 's|nifi.security.truststore=.*|nifi.security.truststore=./conf/truststore.p12|' /opt/nifi/nifi-current/conf/nifi.properties
            sed -i 's|nifi.security.keystorePasswd=.*|nifi.security.keystorePasswd=th1s1s3up34e5r37|' /opt/nifi/nifi-current/conf/nifi.properties
            sed -i 's|nifi.security.truststorePasswd=.*|nifi.security.truststorePasswd=th1s1s3up34e5r37|' /opt/nifi/nifi-current/conf/nifi.properties
            sed -i 's|nifi.security.keyPasswd=.*|nifi.security.keyPasswd=th1s1s3up34e5r37|' /opt/nifi/nifi-current/conf/nifi.properties
            if grep -q "nifi.web.https.sni.host.check" /opt/nifi/nifi-current/conf/nifi.properties; then
              sed -i 's|nifi.web.https.sni.host.check=.*|nifi.web.https.sni.host.check=false|' /opt/nifi/nifi-current/conf/nifi.properties
            else
              echo "nifi.web.https.sni.host.check=false" >> /opt/nifi/nifi-current/conf/nifi.properties
            fi
            sed -i 's|nifi.web.proxy.host=.*|nifi.web.proxy.host=|' /opt/nifi/nifi-current/conf/nifi.properties
            
            # Set credentials
            /opt/nifi/nifi-current/bin/nifi.sh set-single-user-credentials "${NIFI_SINGLE_USER_CREDENTIALS_USERNAME}" "${NIFI_SINGLE_USER_CREDENTIALS_PASSWORD}"

            # Start NiFi
            /opt/nifi/scripts/start.sh
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 11443
          name: cluster
        - containerPort: 8443
          name: https
        - containerPort: 6342
          name: cluster-lb
        env:
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP # Use pod ip
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name # Use pod name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace # Use pod namespace
          - name: NIFI_UI_BANNER_TEXT
            value: $(POD_NAME) # Use pod name for banner
          - name: NIFI_CLUSTER_LOAD_BALANCE_HOST
            value: $(POD_NAME).nifi.$(POD_NAMESPACE).svc.cluster.local # Use pod fqdn as load balance host
          # - name: NIFI_WEB_HTTP_HOST
          #   value: $(POD_NAME).nifi.$(POD_NAMESPACE).svc.cluster.local # Use pod fqdn as web host
          - name: NIFI_CLUSTER_NODE_ADDRESS
            value: $(POD_NAME).nifi.$(POD_NAMESPACE).svc.cluster.local # Use pod fqdn as node address
          - name: NIFI_REMOTE_INPUT_SOCKET_HOST
            value: $(POD_NAME).nifi.$(POD_NAMESPACE).svc.cluster.local # Use pod fqdn as input socket address
          - name: NIFI_REMOTE_INPUT_HOST
            value: $(POD_NAME).nifi.$(POD_NAMESPACE).svc.cluster.local # Use pod fqdn as input host address
          - name: HOSTNAME
            value: $(POD_IP) # Use pod ip as hostname
          - name: NODE_IDENTITY
            value: $(POD_NAME) # Use pod name as identity
          - name: NIFI_SECURITY_KEYSTORE_PASSWD
            value: "th1s1s3up34e5r37"
          - name: NIFI_SECURITY_TRUSTSTORE_PASSWD
            value: "th1s1s3up34e5r37"
          - name: NIFI_SECURITY_KEY_PASSWD
            value: "th1s1s3up34e5r37"
        envFrom:
          - configMapRef:
              name: nifi-cm
              optional: false
        volumeMounts:
          - name: data
            mountPath: /opt/nifi/nifi-current/data
            subPath: data
            readOnly: false
          - name: certs
            mountPath: /opt/nifi/nifi-current/conf/certs
            readOnly: false
          - name: scripts
            mountPath: /scripts/security.sh
            subPath: security.sh
            readOnly: false
        livenessProbe:
          exec:
            command:
              - pgrep
              - java
          initialDelaySeconds: 120
          periodSeconds: 30
          timeoutSeconds: 20
          failureThreshold: 3
          successThreshold: 1
        readinessProbe:
          tcpSocket:
            port: cluster
          initialDelaySeconds: 200
          periodSeconds: 30
          timeoutSeconds: 20
          failureThreshold: 3
          successThreshold: 1
        resources:
          requests:
            cpu: 400m
            memory: 2Gi
          limits:
            cpu: 400m
            memory: 2Gi
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          capabilities:
            drop:
              - ALL
      volumes:
        - name: data
          emptyDir:
            sizeLimit: 3Gi
        - name: certs
          persistentVolumeClaim:
            claimName: nifi-shared-certs
        - name: scripts
          configMap:
            name: nifi-ssl-cm
            optional: false
            defaultMode: 0755
