apiVersion: v1
kind: PersistentVolume
metadata:
  name: nifi-certs-pv
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/nifi-certs
    type: DirectoryOrCreate
